ldes-server-port-ingestion-rest/src/main/java/be/vlaanderen/informatievlaanderen/ldes/server/ingestion/rest/converters/LdesMemberConverter.java, ldes-server-port-ingestion-rest/src/main/java/be/vlaanderen/informatievlaanderen/ldes/server/ingestion/rest/exceptions/MalformedMemberIdException.java
Throw MalformedMemberIdException when MemberType could not be found in listStatements
=> Fix: add MalformedMemberIdException

ldes-fragmentisers/ldes-fragmentisers-geospatial/src/main/java/be/vlaanderen/informatievlaanderen/ldes/server/fragmentisers/geospatial/GeospatialFragmentationStrategy.java
Placement of parallel() in stream doesn't matter apparently. So, collected the stream before executing the next fragmentations in parallel.
See: https://stackoverflow.com/questions/67620445/does-it-matter-where-to-place-parallel-call-in-the-stream-pipeline
=> Fix: concurrent modification operation on geospatial fragmentation

ldes-server-infra-mongo/mongock-changeset-3/src/main/java/be/vlaanderen/informatievlaanderen/ldes/server/infra/mongo/mongock/changeset3/FragmentUpdaterChange.java
Small Bugfix for Mongock Changeset 3 with the introduction of ViewName
=> Fix: Mongock Changeset 3 uses ViewName.asString

ldes-fragmentisers/ldes-fragmentisers-pagination/src/test/java/be/vlaanderen/informatievlaanderen/ldes/server/fragmentisers/pagination/PaginationStrategyTest.java, ldes-fragmentisers/ldes-fragmentisers-pagination/src/test/java/be/vlaanderen/informatievlaanderen/ldes/server/fragmentisers/pagination/PaginationStrategyWrapperTest.java, ldes-fragmentisers/ldes-fragmentisers-pagination/src/test/java/be/vlaanderen/informatievlaanderen/ldes/server/fragmentisers/pagination/services/OpenPageProviderTest.java, ldes-fragmentisers/ldes-fragmentisers-pagination/src/test/java/be/vlaanderen/informatievlaanderen/ldes/server/fragmentisers/pagination/services/PageCreatorTest.java, ldes-server-domain/src/main/java/be/vlaanderen/informatievlaanderen/ldes/server/domain/constants/RdfConstants.java, ldes-server-domain/src/main/java/be/vlaanderen/informatievlaanderen/ldes/server/domain/ldesconfig/services/LdesConfigModelServiceImpl.java, ldes-server-domain/src/main/java/be/vlaanderen/informatievlaanderen/ldes/server/domain/shacl/InMemoryShaclCollection.java, ldes-server-domain/src/main/java/be/vlaanderen/informatievlaanderen/ldes/server/domain/shacl/ShaclCollection.java, ldes-server-domain/src/test/java/be/vlaanderen/informatievlaanderen/ldes/server/domain/shacl/InMemoryShaclCollectionTest.java, ldes-server-port-admin-rest/src/main/java/be/vlaanderen/informatievlaanderen/ldes/server/admin/rest/controllers/AdminShapeRestController.java, ldes-server-port-admin-rest/src/test/java/be/vlaanderen/informatievlaanderen/ldes/server/admin/rest/controllers/AdminShapeRestControllerTest.java, ldes-server-port-admin-rest/src/test/resources/shape-1.ttl, ldes-server-port-admin-rest/src/test/resources/shape-without-type.ttl, ldes-server-port-ingestion-rest/src/main/java/be/vlaanderen/informatievlaanderen/ldes/server/ingestion/rest/LdesMemberIngestionController.java, ldes-server-port-ingestion-rest/src/test/java/be/vlaanderen/informatievlaanderen/ldes/server/ingestion/rest/MemberIngestionControllerTest.java
First step in refactoring the Shacl Admin Controller by:
* Creating an in memory shacl shape collection that reflects the database collection
* redirecting all shacl update and retrieval operations towards this collection
Follow up PR will move away from the use of LdesConfigModel
The Validated issue will be taken up in an issue
=> Feature: Shacl Collection

ldes-server-domain/src/main/java/be/vlaanderen/informatievlaanderen/ldes/server/domain/ldes/retentionpolicy/RetentionPolicyConfig.java, ldes-server-domain/src/main/java/be/vlaanderen/informatievlaanderen/ldes/server/domain/ldes/retentionpolicy/creation/RetentionPolicyCreator.java, ldes-server-domain/src/main/java/be/vlaanderen/informatievlaanderen/ldes/server/domain/ldes/retentionpolicy/creation/RetentionPolicyCreatorImpl.java, ldes-server-domain/src/main/java/be/vlaanderen/informatievlaanderen/ldes/server/domain/ldesfragment/services/FragmentationExecutorImpl.java, ldes-server-domain/src/main/java/be/vlaanderen/informatievlaanderen/ldes/server/domain/ldesfragment/services/TreeNodeRemoverImpl.java, ldes-server-domain/src/main/java/be/vlaanderen/informatievlaanderen/ldes/server/domain/view/InMemoryViewCollection.java, ldes-server-domain/src/main/java/be/vlaanderen/informatievlaanderen/ldes/server/domain/view/valueobject/ViewAddedEvent.java, ldes-server-domain/src/test/java/be/vlaanderen/informatievlaanderen/ldes/server/domain/ldes/retentionpolicy/RetentionPolicyConfigTest.java, ldes-server-domain/src/test/java/be/vlaanderen/informatievlaanderen/ldes/server/domain/ldesfragment/services/FragmentationExecutorImplTest.java, ldes-server-domain/src/test/java/be/vlaanderen/informatievlaanderen/ldes/server/domain/ldesfragment/services/TreeNodeRemoverImplTest.java, ldes-server-domain/src/test/java/be/vlaanderen/informatievlaanderen/ldes/server/domain/view/InMemoryViewCollectionTest.java, ldes-server-port-ingest-rest/src/test/java/be/vlaanderen/informatievlaanderen/ldes/server/ingest/rest/MemberIngestControllerTest.java
Allows to dynamically update the fragmentation process and the retention process with newly added views.
Next steps are:
- update admin api to convert a Model to a ViewSpecification (@pj-cegeka is working on this).
- removing the beans used to create fragmentation strategies and retention policies from config.
=> Feature: Add view dynamically (part 2)

ldes-server-domain/src/main/java/be/vlaanderen/informatievlaanderen/ldes/server/domain/ldesfragment/services/FragmentationExecutorImpl.java, ldes-server-domain/src/main/java/be/vlaanderen/informatievlaanderen/ldes/server/domain/ldesfragment/services/TreeNodeRemoverImpl.java, ldes-server-domain/src/main/java/be/vlaanderen/informatievlaanderen/ldes/server/domain/view/InMemoryViewCollection.java, ldes-server-domain/src/main/java/be/vlaanderen/informatievlaanderen/ldes/server/domain/view/ViewCollection.java, ldes-server-domain/src/main/java/be/vlaanderen/informatievlaanderen/ldes/server/domain/view/repository/ViewRepository.java, ldes-server-domain/src/main/java/be/vlaanderen/informatievlaanderen/ldes/server/domain/view/service/ViewServiceImpl.java, ldes-server-domain/src/main/java/be/vlaanderen/informatievlaanderen/ldes/server/domain/view/valueobject/ViewDeletedEvent.java, ldes-server-domain/src/test/java/be/vlaanderen/informatievlaanderen/ldes/server/domain/ldesfragment/services/FragmentationExecutorImplTest.java, ldes-server-domain/src/test/java/be/vlaanderen/informatievlaanderen/ldes/server/domain/ldesfragment/services/TreeNodeRemoverImplTest.java, ldes-server-domain/src/test/java/be/vlaanderen/informatievlaanderen/ldes/server/domain/view/InMemoryViewCollectionTest.java, ldes-server-domain/src/test/java/be/vlaanderen/informatievlaanderen/ldes/server/domain/view/service/ViewServiceImplTest.java, ldes-server-infra-mongo/mongo-repository/src/main/java/be/vlaanderen/informatievlaanderen/ldes/server/infra/mongo/view/ViewMongoRepository.java, ldes-server-infra-mongo/mongo-repository/src/test/java/be/vlaanderen/informatievlaanderen/ldes/server/infra/mongo/view/ViewMongoRepositoryTest.java
Support to delete a view from a collection. This will update the viewrepository and disable fragmentation and retention processes of that view.
Next steps:
* go over all the TODO's, highest priority = side effects of adding/deleting a view such as creating a root node for that view, refragmenting all existing members of the collection, deleting all fragments of a deleted view
=> Feature: Delete view from collection

ldes-server-domain/src/main/java/be/vlaanderen/informatievlaanderen/ldes/server/domain/ldesfragment/services/FragmentationExecutorImpl.java, ldes-server-domain/src/main/java/be/vlaanderen/informatievlaanderen/ldes/server/domain/ldesfragment/services/FragmentationStrategyCollection.java, ldes-server-domain/src/main/java/be/vlaanderen/informatievlaanderen/ldes/server/domain/ldesfragment/services/FragmentationStrategyCollectionImpl.java, ldes-server-domain/src/main/java/be/vlaanderen/informatievlaanderen/ldes/server/domain/view/InMemoryViewCollection.java, ldes-server-domain/src/test/java/be/vlaanderen/informatievlaanderen/ldes/server/domain/ldesfragment/services/FragmentationExecutorImplTest.java, ldes-server-domain/src/test/java/be/vlaanderen/informatievlaanderen/ldes/server/domain/ldesfragment/services/FragmentationStrategyCollectionImplTest.java
Isolated the FragmentationStrategyCollection.
The objective is to let that object be responsible for the correct adding and deleting of views.
In this PR that the creation of a root node is included.
In follow-up PRs:
* adding will also refragment old members
* deleting will also delete LdesFragments of the view.
=> Feature: VSDSPUB-668: Create Root Node for new View

ldes-server-domain/src/main/java/be/vlaanderen/informatievlaanderen/ldes/server/domain/ldes/retentionpolicy/RetentionPolicy.java, ldes-server-domain/src/main/java/be/vlaanderen/informatievlaanderen/ldes/server/domain/ldes/retentionpolicy/versionbased/ReverseTimeStampComparator.java, ldes-server-domain/src/main/java/be/vlaanderen/informatievlaanderen/ldes/server/domain/ldes/retentionpolicy/versionbased/VersionBasedRetentionPolicy.java, ldes-server-domain/src/main/java/be/vlaanderen/informatievlaanderen/ldes/server/domain/tree/member/repository/MemberRepository.java, ldes-server-domain/src/test/java/be/vlaanderen/informatievlaanderen/ldes/server/domain/ldes/retentionpolicy/versionbased/VersionBasedRetentionPolicyTest.java, ldes-server-infra-mongo/mongo-repository/src/main/java/be/vlaanderen/informatievlaanderen/ldes/server/infra/mongo/member/MemberMongoRepository.java, ldes-server-infra-mongo/mongo-repository/src/test/java/be/vlaanderen/informatievlaanderen/ldes/server/infra/mongo/MemberMongoRepositoryTest.java
Provided an implementation of VersionBasedRetentionPolicy that:
- implements the RetentionPolicy interface
- returns false if the tested Member does not have the timestamp or versionOf attribute
- Otherwise: returns false for the amountOfMembersToKeep most recent members and true for the other members (which makes them a candidate for removal).
Note: There's possibly a more efficient implementation possible which only retrieves the members with the same versionOf attribute once, but I prefer this implementation because:
- it acts on the member (similar as defined in the spec)
- it fits in the current retention policy implementation
- retention is so far never a resource (memory/cpu/iops) critical process, so there's no big need for optimizations.
=> Feature: VSDSPUB-712: Implement Version Based Retention Policy

ldes-server-domain/src/main/java/be/vlaanderen/informatievlaanderen/ldes/server/domain/eventstream/services/EventStreamServiceImpl.java, ldes-server-domain/src/main/java/be/vlaanderen/informatievlaanderen/ldes/server/domain/view/service/ViewServiceImpl.java, ldes-server-domain/src/test/java/be/vlaanderen/informatievlaanderen/ldes/server/domain/view/service/ViewServiceImplTest.java, ldes-server-port-admin-rest/src/main/java/be/vlaanderen/informatievlaanderen/ldes/server/admin/rest/controllers/AdminViewsRestController.java, ldes-server-port-admin-rest/src/main/java/be/vlaanderen/informatievlaanderen/ldes/server/admin/rest/controllers/OpenApiAdminViewsRestController.java, ldes-server-port-admin-rest/src/main/java/be/vlaanderen/informatievlaanderen/ldes/server/admin/rest/converters/ListViewHttpConverter.java, ldes-server-port-admin-rest/src/main/java/be/vlaanderen/informatievlaanderen/ldes/server/admin/rest/converters/ViewHttpConverter.java, ldes-server-port-admin-rest/src/main/java/be/vlaanderen/informatievlaanderen/ldes/server/admin/rest/exceptionhandling/AdminRestResponseEntityExceptionHandler.java, ldes-server-port-admin-rest/src/test/java/be/vlaanderen/informatievlaanderen/ldes/server/admin/rest/controllers/AdminViewsRestControllerTest.java, ldes-server-port-admin-rest/src/test/java/be/vlaanderen/informatievlaanderen/ldes/server/admin/rest/controllers/integration/AdminEventStreamsRestControllerSteps.java
In this PR:
* examples and documentation for adding, getting and deleting views via the Admin interface
* Saving an eventstream triggers also the saving of viewspecifications
* Saving an eventstream sends out an `EventStreamChangedEvent`
* Checks in the `ViewServiceImpl` to verify that eventstreams exists when adding, retrieving or deleting views
* Check in the `ViewServiceImpl` to verify that view exists before deleting
* Put -> Post for creating View
=> Feature: Added example to Open API Admin View

ldes-server-domain/src/main/java/be/vlaanderen/informatievlaanderen/ldes/server/domain/tree/member/repository/MemberRepository.java, ldes-server-domain/src/main/java/be/vlaanderen/informatievlaanderen/ldes/server/domain/tree/member/services/MemberIngestServiceImpl.java, ldes-server-domain/src/test/java/be/vlaanderen/informatievlaanderen/ldes/server/domain/tree/member/services/MemberIngestServiceImplTest.java, ldes-server-infra-mongo/mongo-repository/src/main/java/be/vlaanderen/informatievlaanderen/ldes/server/infra/mongo/member/MemberMongoRepository.java, ldes-server-infra-mongo/mongo-repository/src/main/java/be/vlaanderen/informatievlaanderen/ldes/server/infra/mongo/member/repository/LdesMemberEntityRepository.java, ldes-server-infra-mongo/mongo-repository/src/test/java/be/vlaanderen/informatievlaanderen/ldes/server/infra/mongo/member/MemberRepositorySteps.java, ldes-server-infra-mongo/mongo-repository/src/test/resources/features/member/member.feature
Now in the original domain module, all members of a certain collection can be deleted at once
=> bugfix: more performant way to delete all members of a collection

ldes-server-infra-mongo/mongo-retention-repository/src/test/java/be/vlaanderen/informatievlaanderen/ldes/server/retention/MemberPropertiesRepositorySteps.java, ldes-server-retention/pom.xml, ldes-server-retention/src/main/java/be/vlaanderen/informatievlaanderen/ldes/server/retention/repositories/MemberPropertiesRepository.java, ldes-server-retention/src/test/java/be/vlaanderen/informatievlaanderen/ldes/server/retention/integrationtest/RetentionIT.java, ldes-server-retention/src/test/java/be/vlaanderen/informatievlaanderen/ldes/server/retention/integrationtest/RetentionIntegrationTest.java, ldes-server-retention/src/test/java/be/vlaanderen/informatievlaanderen/ldes/server/retention/integrationtest/RetentionServiceSteps.java, ldes-server-retention/src/test/java/be/vlaanderen/informatievlaanderen/ldes/server/retention/integrationtest/stub/InMemoryMemberPropertiesRepository.java, ldes-server-retention/src/test/resources/features/data/memberTemplate.ttl, ldes-server-retention/src/test/resources/features/retention.feature, ldes-server-retention/src/test/resources/retentionpolicy/pointintime/valid_pointintime.ttl, ldes-server-retention/src/test/resources/retentionpolicy/timebased/valid_timebased.ttl
Created an integration test for the retention module that acts on the captured events and tests the following policies:
* time-based
* version-based
* point-in-time
On a technical note: It is not possible to capture the outgoing MemberUnallocatedEvents and MemberDeletedEvents, because in the test set-up these are fired in a separate thread (due to the scheduling) and they cannot be captured with the spring test mechanism `ApplicationEvents`, since the test mechanism `ApplicationEventsApplicationListener` is not registered to that thread. Hence, the removal of members from views is verified using the database.
=> Feat: Provide complete integration test for the retention module

Dockerfile
Replaces PR https://github.com/Informatievlaanderen/VSDS-LDESServer4J/pull/492
Fixes https://github.com/Informatievlaanderen/VSDS-LDESServer4J/issues/779
Note that we go from java 18 to java 17. This is because there is only LTS for java 17 and 21 but the server can currently only support up to java 20. We don't lose anything by going "back" to v17
=> fix: replace deprecated jdk in docker build

README.md
Removed the reference to Swagger documentation since the reference referenced to nowhere.
=> docs: [skip ci] : Update README.md

ldes-server-retention/src/main/java/be/vlaanderen/informatievlaanderen/ldes/server/retention/config/AsyncConfig.java, ldes-server-retention/src/main/java/be/vlaanderen/informatievlaanderen/ldes/server/retention/services/DeleteEventHandler.java, ldes-server-retention/src/main/java/be/vlaanderen/informatievlaanderen/ldes/server/retention/services/ViewAddedHandler.java, ldes-server-retention/src/test/java/be/vlaanderen/informatievlaanderen/ldes/server/retention/integrationtest/stub/InMemoryMemberPropertiesRepository.java
When a view is added or deleted to a collection with a large amount of members, it takes forever to perform this action, due to the allocation and unallocation of members to a view. This is now made asynchronous
=> fix: slow view operations

ldes-server-admin/src/main/java/be/vlaanderen/informatievlaanderen/ldes/server/admin/domain/view/repository/DcatViewRepository.java, ldes-server-admin/src/main/java/be/vlaanderen/informatievlaanderen/ldes/server/admin/domain/view/service/DcatViewServiceImpl.java, ldes-server-admin/src/main/java/be/vlaanderen/informatievlaanderen/ldes/server/admin/domain/view/service/ViewServiceImpl.java, ldes-server-admin/src/test/java/be/vlaanderen/informatievlaanderen/ldes/server/admin/domain/view/service/ViewServiceImplTest.java, ldes-server-compaction/src/main/java/be/vlaanderen/informatievlaanderen/ldes/server/compaction/application/eventhandlers/ViewCapacityDeleter.java, ldes-server-compaction/src/main/java/be/vlaanderen/informatievlaanderen/ldes/server/compaction/domain/repository/ViewCollection.java, ldes-server-compaction/src/main/java/be/vlaanderen/informatievlaanderen/ldes/server/compaction/domain/repository/ViewCollectionImpl.java, ldes-server-compaction/src/test/java/be/vlaanderen/informatievlaanderen/ldes/server/compaction/domain/repository/ViewCollectionImplTest.java, ldes-server-infra-mongo/mongo-admin-repository/src/main/java/be/vlaanderen/informatievlaanderen/ldes/server/admin/mongo/MongoAdminAutoConfiguration.java, ldes-server-infra-mongo/mongo-admin-repository/src/main/java/be/vlaanderen/informatievlaanderen/ldes/server/admin/mongo/view/DcatViewMongoRepository.java, ldes-server-infra-mongo/mongo-admin-repository/src/main/java/be/vlaanderen/informatievlaanderen/ldes/server/admin/mongo/view/repository/DataServiceEntityRepository.java, ldes-server-infra-mongo/mongo-admin-repository/src/test/java/be/vlaanderen/informatievlaanderen/ldes/server/admin/mongo/SpringIntegrationTest.java, ldes-server-infra-mongo/mongo-admin-repository/src/test/java/be/vlaanderen/informatievlaanderen/ldes/server/admin/mongo/view/DcatViewRepositorySteps.java, ldes-server-infra-mongo/mongo-admin-repository/src/test/resources/features/view/dcatview.feature, ldes-server-infra-mongo/mongo-fetch-repository/src/main/java/be/vlaanderen/informatievlaanderen/ldes/server/fetch/AllocationMongoRepository.java, ldes-server-port-fetch-rest/src/main/java/be/vlaanderen/informatievlaanderen/ldes/server/rest/treenode/services/TreeNodeConverterImpl.java, ldes-server-port-fetch-rest/src/test/java/be/vlaanderen/informatievlaanderen/ldes/server/rest/treenode/services/TreeNodeConverterImplTest.java, ldes-server-port-fetch/src/main/java/be/vlaanderen/informatievlaanderen/ldes/server/fetching/eventhandler/ViewDeletedHandlerFetch.java, ldes-server-retention/src/main/java/be/vlaanderen/informatievlaanderen/ldes/server/retention/repositories/RetentionPolicyCollectionImpl.java, ldes-server-retention/src/main/java/be/vlaanderen/informatievlaanderen/ldes/server/retention/repositories/ViewCollection.java, ldes-server-retention/src/test/java/be/vlaanderen/informatievlaanderen/ldes/server/retention/repositories/RetentionPolicyCollectionImplTest.java, ldes-server-retention/src/test/java/be/vlaanderen/informatievlaanderen/ldes/server/retention/repositories/ViewCollectionTest.java
Before this fix, when an event stream was deleted, both the EventStreamDeletedEvent and ViewDeletedEvent were sent out, resulting that at some places in the code, both events were received and executed some logic twice
=> fix: members deleted twice

ldes-server-application/src/main/java/be/vlaanderen/informatievlaanderen/ldes/server/config/ActuatorHostNameCustomizer.java
In https://github.com/Informatievlaanderen/VSDS-LDESServer4J/issues/1029, it was described that the actuator uses the internal addresses, which makes sense, as Spring Boot uses this internal address everywhere. This has now been fixed, where the property `ldes-server.host-name` is used to bind the internal address to this, which replaces the functionality of the already existing property `server.address`. 
This change comes with the precaution that the application will not startup when the server cannot be bound to `ldes-server.host-name`.
=> fix: actuator uses internal addresses

docs/_sass/_layout.scss, docs/_sass/theme.scss
When the screen width exceeds 66.5rem, the padding is reduced to maximize the available screen real estate for the documentation content.
=> docs: reduce documentation padding

README.md
Changed metrics url from "/actuator/metrics" to "/actuator/prometheus"
=> doc: change of metrics URL

ldes-server-ingest/ldes-server-ingest-common/src/main/java/be/vlaanderen/informatievlaanderen/ldes/server/ingest/validators/ingestreportvalidator/PathsValidator.java, ldes-server-ingest/ldes-server-ingest-common/src/main/java/module-info.java, ldes-server-ingest/ldes-server-ingest-rest/src/test/java/be/vlaanderen/informatievlaanderen/ldes/server/ingest/rest/MemberIngestControllerTest.java, ldes-server-ingest/ldes-server-ingest-rest/src/test/java/be/vlaanderen/informatievlaanderen/ldes/server/ingest/rest/validators/memberingestvalidator/MemberIngestValidatorTest.java
This pull request includes several changes to the `ldes-server-ingest` module, primarily focusing on improving validation logic and updating dependencies. The most important changes include modifications to the `PathsValidator` class, updates to the module dependencies, and adjustments to the test cases in `MemberIngestValidatorTest`.
* [`PathsValidator.java`](diffhunk://#diff-063006619271fcae86f7156df39bddf8241e3d1a8f00eccc22bf469b879803d8L6-R25): Modified the `validate` method to use `listSubjectsWithProperty` instead of `listSubjects`, enhancing the logic for filtering subjects based on the `eventStream` version path.
* [`PathsValidator.java`](diffhunk://#diff-063006619271fcae86f7156df39bddf8241e3d1a8f00eccc22bf469b879803d8L73-R80): Updated the `getStatementsOfPath` method to use …
=> fix: lenient version ingest

ldes-server-infra-postgres/postgres-ingest-repository/src/main/java/be/vlaanderen/informatievlaanderen/ldes/server/ingest/postgres/MemberPostgresRepository.java
fix: lock collection row to prevent interleaved sequence numbers in member_id when ingesting members
=> fix: missing members when ingesting multi-threaded

ldes-server-infra-postgres/postgres-admin-repository/src/main/java/be/vlaanderen/informatievlaanderen/ldes/server/admin/postgres/dcatserver/DcatCatalogPostgresRepository.java, ldes-server-infra-postgres/postgres-admin-repository/src/test/java/be/vlaanderen/informatievlaanderen/ldes/server/admin/postgres/dcatserver/DcatServerPostgresRepositoryTest.java, ldes-server-integration-test/src/test/java/be/vlaanderen/informatievlaanderen/ldes/server/FragmentationSteps.java
Cleanup of Dcat catalog repo [1284](https://github.com/Informatievlaanderen/VSDS-LDESServer4J/issues/1284)
=> chore: dcat catalog repository: remove unreachable logic
