Informatievlaanderen/VSDS-LDESServer4J

VSDS-LDESServer4J-application/pom.xml
VSDS-LDESServer4J-application/src/main/java/be/vlaanderen/informatievlaanderen/ldes/server/Application.java
VSDS-LDESServer4J-application/src/main/resources/application.yml
VSDS-LDESServer4J-domain/pom.xml
VSDS-LDESServer4J-domain/src/main/java/be/vlaanderen/informatievlaanderen/ldes/server/domain/services/LdesFragmentRepository.java
VSDS-LDESServer4J-domain/src/main/java/be/vlaanderen/informatievlaanderen/ldes/server/domain/services/LdesFragmentService.java
VSDS-LDESServer4J-domain/src/test/java/be/vlaanderen/informatievlaanderen/ldes/server/domain/services/LdesFragmentServiceTest.java
VSDS-LDESServer4J-infra-mongo/pom.xml
VSDS-LDESServer4J-infra-mongo/src/main/java/be/vlaanderen/informatievlaanderen/ldes/server/infra/mongo/LdesFragmentStorageService.java
VSDS-LDESServer4J-infra-mongo/src/main/java/be/vlaanderen/informatievlaanderen/ldes/server/infra/mongo/entity/LdesFragmentEntity.java
VSDS-LDESServer4J-infra-mongo/src/main/java/be/vlaanderen/informatievlaanderen/ldes/server/infra/mongo/repository/LdesFragmentMongoRepository.java
VSDS-LDESServer4J-infra-mongo/src/test/java/be/vlaanderen/informatievlaanderen/ldes/server/infra/mongo/LdesFragmentStorageServiceTest.java
VSDS-LDESServer4J-interface-rest/pom.xml
VSDS-LDESServer4J-interface-rest/src/main/java/be/vlaanderen/informatievlaanderen/ldes/server/port/rest/LdesFragmentController.java
VSDS-LDESServer4J-interface-rest/src/test/java/be/vlaanderen/informatievlaanderen/ldes/server/port/rest/LdesFragmentControllerTest.java
VSDS-LDESServer4J-interface-rest/src/test/java/be/vlaanderen/informatievlaanderen/ldes/server/port/rest/TestConfiguration.java
pom.xml

Example implementation LDES Server without pagination
(will create PR with pagination right away)

Initial implementation of framework

---

.gitignore
VSDS-LDESServer4J-application/pom.xml
VSDS-LDESServer4J-application/src/main/java/be/vlaanderen/informatievlaanderen/ldes/server/Application.java
VSDS-LDESServer4J-application/src/main/resources/application.yml
VSDS-LDESServer4J-domain/pom.xml
VSDS-LDESServer4J-domain/src/main/java/be/vlaanderen/informatievlaanderen/ldes/server/domain/services/LdesFragmentRepository.java
VSDS-LDESServer4J-domain/src/main/java/be/vlaanderen/informatievlaanderen/ldes/server/domain/services/LdesFragmentService.java
VSDS-LDESServer4J-domain/src/test/java/be/vlaanderen/informatievlaanderen/ldes/server/domain/services/LdesFragmentServiceTest.java
VSDS-LDESServer4J-infra-mongo/pom.xml
VSDS-LDESServer4J-infra-mongo/src/main/java/be/vlaanderen/informatievlaanderen/ldes/server/infra/mongo/LdesFragmentCreator.java
VSDS-LDESServer4J-infra-mongo/src/main/java/be/vlaanderen/informatievlaanderen/ldes/server/infra/mongo/LdesFragmentStorageService.java
VSDS-LDESServer4J-infra-mongo/src/main/java/be/vlaanderen/informatievlaanderen/ldes/server/infra/mongo/config/EndpointConfiguration.java
VSDS-LDESServer4J-infra-mongo/src/main/java/be/vlaanderen/informatievlaanderen/ldes/server/infra/mongo/entity/LdesFragmentEntity.java
VSDS-LDESServer4J-infra-mongo/src/main/java/be/vlaanderen/informatievlaanderen/ldes/server/infra/mongo/repository/LdesFragmentMongoRepository.java
VSDS-LDESServer4J-infra-mongo/src/test/java/be/vlaanderen/informatievlaanderen/ldes/server/infra/mongo/LdesFragmentStorageServiceTest.java
VSDS-LDESServer4J-interface-rest/pom.xml
VSDS-LDESServer4J-interface-rest/src/main/java/be/vlaanderen/informatievlaanderen/ldes/server/port/rest/LdesFragmentController.java
VSDS-LDESServer4J-interface-rest/src/test/java/be/vlaanderen/informatievlaanderen/ldes/server/port/rest/LdesFragmentControllerTest.java
VSDS-LDESServer4J-interface-rest/src/test/java/be/vlaanderen/informatievlaanderen/ldes/server/port/rest/TestConfiguration.java
pom.xml

Draft implementation of the paginated response.
To be merged after #4

Paginated response

---

.github/workflows/push-build-and-test.yml
VSDS-LDESServer4J-application/pom.xml

GitHub Action to build and run tests when pushing to a branch ('master' branch excluded as we shouldn't push directly on it). Is also active when creating a PR.

Add GitHub Action to build and test

---

VSDS-LDESServer4J-domain/src/main/java/be/vlaanderen/informatievlaanderen/ldes/server/domain/services/LdesFragmentService.java
VSDS-LDESServer4J-domain/src/test/java/be/vlaanderen/informatievlaanderen/ldes/server/domain/services/LdesFragmentServiceTest.java
VSDS-LDESServer4J-infra-mongo/src/main/java/be/vlaanderen/informatievlaanderen/ldes/server/infra/mongo/LdesFragmentCreator.java
VSDS-LDESServer4J-infra-mongo/src/main/java/be/vlaanderen/informatievlaanderen/ldes/server/infra/mongo/LdesFragmentStorageService.java
VSDS-LDESServer4J-infra-mongo/src/main/java/be/vlaanderen/informatievlaanderen/ldes/server/infra/mongo/config/EndpointConfiguration.java
VSDS-LDESServer4J-infra-mongo/src/test/java/be/vlaanderen/informatievlaanderen/ldes/server/infra/mongo/LdesFragmentStorageServiceTest.java
VSDS-LDESServer4J-interface-rest/src/main/java/be/vlaanderen/informatievlaanderen/ldes/server/port/rest/LdesFragmentController.java
VSDS-LDESServer4J-interface-rest/src/test/java/be/vlaanderen/informatievlaanderen/ldes/server/port/rest/LdesFragmentControllerTest.java
pom.xml

added formatter plugin

---

.github/workflows/push-build-and-test.yml

Updated gh action so that it won't build on every push

Updated gh action

---

VSDS-LDESServer4J-infra-mongo/mongo-repository-library/src/main/java/be/vlaanderen/informatievlaanderen/ldes/server/infra/mongo/config/MongoMapKeyDotReplacementConfiguration.java

Allow LDES server to accept and store the GIPOD stream. (contains dot in key)

---

Dockerfile
config.local.env
docker-compose.yml
pom.xml

- Updated formatter plugin
- Updated docker-compose.yml

feat: Updated formatter plugin + docker-compose.yml

---

ldes-server-infra-mongo/mongo-repository-spring-boot-autoconfigure/pom.xml
ldes-server-infra-mongo/mongo-repository-spring-boot-autoconfigure/src/test/java/be/vlaanderen/informatievlaanderen/ldes/server/infra/mongo/SpringContextTest.java

fix: Bom issues

---

.github/workflows/pr-build.yml

feat: Updated CI for PR from feature to main (Typo)

---

ldes-server-application/pom.xml
ldes-server-domain/pom.xml
ldes-server-infra-mongo/pom.xml
ldes-server-port-ingestion-rest/pom.xml
ldes-server-port-publication-rest/pom.xml
pom.xml

chore: remove BOM - added dependencies for other PR's
chore: remove 'agressive' comment headers

chore: remove BOM

---

.github/workflows/pr-build.yml
docker-compose/config.local.env
ldes-server-domain/src/main/java/be/vlaanderen/informatievlaanderen/ldes/server/domain/entities/LdesFragment.java
ldes-server-port-publication-rest/src/main/java/be/vlaanderen/informatievlaanderen/ldes/server/rest/config/LdesConfig.java
ldes-server-port-publication-rest/src/main/java/be/vlaanderen/informatievlaanderen/ldes/server/rest/services/JsonObjectCreatorImpl.java
ldes-server-port-publication-rest/src/test/java/be/vlaanderen/informatievlaanderen/ldes/server/rest/LdesFragmentControllerTest.java
ldes-server-port-publication-rest/src/test/java/be/vlaanderen/informatievlaanderen/ldes/server/rest/TestConfiguration.java
ldes-server-port-publication-rest/src/test/java/be/vlaanderen/informatievlaanderen/ldes/server/rest/services/JsonObjectCreatorImplTest.java

feat: Updated CI for PR from feature to main
fix: merge conflicts

Add shape to fragment

---

ldes-server-application/pom.xml
ldes-server-domain/src/main/java/be/vlaanderen/informatievlaanderen/ldes/server/domain/config/ViewConfig.java
ldes-server-domain/src/main/java/be/vlaanderen/informatievlaanderen/ldes/server/domain/converter/FragmentIdConverter.java
ldes-server-domain/src/main/java/be/vlaanderen/informatievlaanderen/ldes/server/domain/entities/LdesMember.java
ldes-server-domain/src/main/java/be/vlaanderen/informatievlaanderen/ldes/server/domain/entities/TreeRelation.java
ldes-server-domain/src/main/java/be/vlaanderen/informatievlaanderen/ldes/server/domain/services/FragmentationServiceImpl.java
ldes-server-domain/src/test/java/be/vlaanderen/informatievlaanderen/ldes/server/domain/services/FragmentIdConverterTest.java

* Removed usage of regex
* introduced maven profile for quick development

fix: Code cleanup:

---

ldes-server-domain/src/main/java/be/vlaanderen/informatievlaanderen/ldes/server/domain/ldesmember/entities/LdesMember.java
ldes-server-infra-mongo/src/main/java/be/vlaanderen/informatievlaanderen/ldes/server/infra/mongo/LdesFragmentMongoRepository.java
ldes-server-infra-mongo/src/main/java/be/vlaanderen/informatievlaanderen/ldes/server/infra/mongo/MongoAutoConfiguration.java
ldes-server-infra-mongo/src/main/java/be/vlaanderen/informatievlaanderen/ldes/server/infra/mongo/repositories/LdesFragmentEntityRepository.java
ldes-server-infra-mongo/src/test/java/be/vlaanderen/informatievlaanderen/ldes/server/infra/mongo/LdesFragmentMongoRepositoryTest.java

* fixed deletion of Tree member when it does not exist
* started rewriting mongo queries to reduce querying entire db

feat: improve server performance:

---

pom.xml

Reverts Informatievlaanderen/VSDS-LDESServer4J#145

Revert "build(deps-dev): bump awaitility from 3.0.0 to 4.2.0"

---

ldes-fragmentisers/ldes-fragmentisers-geospatial/src/main/java/be/vlaanderen/informatievlaanderen/ldes/fragmentisers/geospatial/connected/relations/GeospatialRelationsAttributer.java
ldes-fragmentisers/ldes-fragmentisers-geospatial/src/main/java/be/vlaanderen/informatievlaanderen/ldes/fragmentisers/geospatial/constants/GeospatialConstants.java
ldes-fragmentisers/ldes-fragmentisers-geospatial/src/test/java/be/vlaanderen/informatievlaanderen/ldes/fragmentisers/geospatial/connected/relations/GeospatialRelationsAttributerTest.java
ldes-fragmentisers/ldes-fragmentisers-sequential/ldes-fragmentisers-sequential-timebased/src/main/java/be/vlaanderen/informatievlaanderen/ldes/fragmentisers/timebased/TimeBasedFragmentCreator.java
ldes-fragmentisers/ldes-fragmentisers-sequential/ldes-fragmentisers-sequential-timebased/src/test/java/be/vlaanderen/informatievlaanderen/ldes/fragmentisers/timebased/TimeBasedFragmentCreatorTest.java
ldes-server-domain/src/main/java/be/vlaanderen/informatievlaanderen/ldes/server/domain/exceptions/RdfFormatException.java
ldes-server-domain/src/main/java/be/vlaanderen/informatievlaanderen/ldes/server/domain/ldesfragment/services/LdesFragmentConverterImpl.java
ldes-server-domain/src/main/java/be/vlaanderen/informatievlaanderen/ldes/server/domain/ldesfragment/valueobjects/TreeRelation.java
ldes-server-domain/src/test/java/be/vlaanderen/informatievlaanderen/ldes/server/domain/converter/LdesFragmentConverterImplTest.java
ldes-server-domain/src/test/java/be/vlaanderen/informatievlaanderen/ldes/server/domain/entities/TreeRelationTest.java
ldes-server-port-fetch-rest/src/main/java/be/vlaanderen/informatievlaanderen/ldes/server/rest/LdesFragmentController.java
ldes-server-port-fetch-rest/src/main/java/be/vlaanderen/informatievlaanderen/ldes/server/rest/converters/LdesFragmentHttpConverter.java
ldes-server-port-fetch-rest/src/test/java/be/vlaanderen/informatievlaanderen/ldes/server/rest/LdesFragmentControllerTest.java

Added types to the tree relation values.

feat: VSDSPUB-241: Typed Values for TreeRelation (needed to support different fragmentations)

---

README.md
ldes-server-domain/src/main/java/be/vlaanderen/informatievlaanderen/ldes/server/domain/viewcreation/valueobjects/ViewConfig.java
ldes-server-domain/src/test/java/be/vlaanderen/informatievlaanderen/ldes/server/domain/viewcreation/valueobjects/ViewConfigTest.java
ldes-server-domain/src/test/resources/application-view-config-test.yml

Added solution to always have one default view where pagination is used with 100 members per page

Feat: Added Default Pagination View

---

docker-compose/config.local.env

Fix: Config Local Mongock

---

Dockerfile
docker-compose/config.local.env
ldes-server-application/pom.xml
ldes-server-infra-mongo/mongock-changeset-2/src/main/java/be/vlaanderen/informatievlaanderen/ldes/server/infra/mongo/mongock/changeset2/entities/LocalDateTimeConverter.java
ldes-server-infra-mongo/mongock-changeset-3/README.md
ldes-server-infra-mongo/mongock-changeset-3/pom.xml
ldes-server-infra-mongo/mongock-changeset-3/src/main/java/be/vlaanderen/informatievlaanderen/ldes/server/infra/mongo/mongock/changeset3/FragmentUpdaterChange.java
ldes-server-infra-mongo/mongock-changeset-3/src/main/java/be/vlaanderen/informatievlaanderen/ldes/server/infra/mongo/mongock/changeset3/LdesMemberEntityV4Listener.java
ldes-server-infra-mongo/mongock-changeset-3/src/main/java/be/vlaanderen/informatievlaanderen/ldes/server/infra/mongo/mongock/changeset3/MemberUpdaterChange.java
ldes-server-infra-mongo/mongock-changeset-3/src/main/java/be/vlaanderen/informatievlaanderen/ldes/server/infra/mongo/mongock/changeset3/entities/LdesFragmentEntityV2.java
ldes-server-infra-mongo/mongock-changeset-3/src/main/java/be/vlaanderen/informatievlaanderen/ldes/server/infra/mongo/mongock/changeset3/entities/LdesFragmentEntityV3.java
ldes-server-infra-mongo/mongock-changeset-3/src/main/java/be/vlaanderen/informatievlaanderen/ldes/server/infra/mongo/mongock/changeset3/entities/LdesMemberEntityV3.java
ldes-server-infra-mongo/mongock-changeset-3/src/main/java/be/vlaanderen/informatievlaanderen/ldes/server/infra/mongo/mongock/changeset3/entities/LdesMemberEntityV4.java
ldes-server-infra-mongo/mongock-changeset-3/src/main/java/be/vlaanderen/informatievlaanderen/ldes/server/infra/mongo/mongock/changeset3/entities/MemberSequenceEntityV1.java
ldes-server-infra-mongo/mongock-changeset-3/src/main/java/be/vlaanderen/informatievlaanderen/ldes/server/infra/mongo/mongock/changeset3/membersequence/entity/MemberSequenceEntityV1.java
ldes-server-infra-mongo/mongock-changeset-3/src/main/java/be/vlaanderen/informatievlaanderen/ldes/server/infra/mongo/mongock/changeset3/membersequence/service/MongockSequenceGeneratorService.java
ldes-server-infra-mongo/mongock-changeset-3/src/main/java/be/vlaanderen/informatievlaanderen/ldes/server/infra/mongo/mongock/changeset3/valueobjects/FragmentPair.java
ldes-server-infra-mongo/mongock-changeset-3/src/main/java/be/vlaanderen/informatievlaanderen/ldes/server/infra/mongo/mongock/changeset3/valueobjects/TreeRelation.java
ldes-server-infra-mongo/pom.xml

Mongock changeset for:
* adding `collectionName` to member and fragments
* imposing an order by adding `sequenceNr` to member (and the creation of the member sequence collection)

Feature: VSDSPUB-615 Mongock

---

ldes-server-domain/src/main/java/be/vlaanderen/informatievlaanderen/ldes/server/domain/view/InMemoryViewCollection.java
ldes-server-domain/src/main/java/be/vlaanderen/informatievlaanderen/ldes/server/domain/view/ViewCollection.java
ldes-server-domain/src/main/java/be/vlaanderen/informatievlaanderen/ldes/server/domain/view/exception/DuplicateViewException.java
ldes-server-domain/src/main/java/be/vlaanderen/informatievlaanderen/ldes/server/domain/view/repository/ViewRepository.java
ldes-server-domain/src/main/java/be/vlaanderen/informatievlaanderen/ldes/server/domain/view/service/ViewService.java
ldes-server-domain/src/main/java/be/vlaanderen/informatievlaanderen/ldes/server/domain/view/service/ViewServiceImpl.java
ldes-server-domain/src/main/java/be/vlaanderen/informatievlaanderen/ldes/server/domain/viewcreation/valueobjects/ViewSpecification.java
ldes-server-domain/src/test/java/be/vlaanderen/informatievlaanderen/ldes/server/domain/view/InMemoryViewCollectionTest.java
ldes-server-domain/src/test/java/be/vlaanderen/informatievlaanderen/ldes/server/domain/view/service/ViewServiceImplTest.java
ldes-server-domain/src/test/java/be/vlaanderen/informatievlaanderen/ldes/server/domain/viewcreation/valueobjects/ViewSpecificationTest.java
ldes-server-infra-mongo/mongo-repository/src/main/java/be/vlaanderen/informatievlaanderen/ldes/server/infra/mongo/MongoAutoConfiguration.java
ldes-server-infra-mongo/mongo-repository/src/main/java/be/vlaanderen/informatievlaanderen/ldes/server/infra/mongo/view/ViewMongoRepository.java
ldes-server-infra-mongo/mongo-repository/src/main/java/be/vlaanderen/informatievlaanderen/ldes/server/infra/mongo/view/entity/ViewEntity.java
ldes-server-infra-mongo/mongo-repository/src/main/java/be/vlaanderen/informatievlaanderen/ldes/server/infra/mongo/view/repository/ViewEntityRepository.java
ldes-server-infra-mongo/mongo-repository/src/main/java/be/vlaanderen/informatievlaanderen/ldes/server/infra/mongo/view/service/ViewEntityConverter.java
ldes-server-infra-mongo/mongo-repository/src/test/java/be/vlaanderen/informatievlaanderen/ldes/server/infra/mongo/view/ViewMongoRepositoryTest.java
ldes-server-port-admin-rest/src/main/java/be/vlaanderen/informatievlaanderen/ldes/server/admin/rest/controllers/AdminViewsRestController.java
ldes-server-port-admin-rest/src/test/java/be/vlaanderen/informatievlaanderen/ldes/server/admin/rest/controllers/AdminViewsRestControllerTest.java

Support to add view to a collection. 
The current implementation will save a ViewSpecification in the datase.
Next steps are:
* update admin api to convert a Model to a ViewSpecification (@pj-cegeka  is working on this)
* sending out events and listening to them in the relevant components
* go over TODO's

Add View To Collection (part 1)

---

ldes-server-domain/src/main/java/be/vlaanderen/informatievlaanderen/ldes/server/domain/events/ShaclDeletedEvent.java
ldes-server-domain/src/main/java/be/vlaanderen/informatievlaanderen/ldes/server/domain/shacl/InMemoryShaclCollection.java
ldes-server-domain/src/main/java/be/vlaanderen/informatievlaanderen/ldes/server/domain/view/InMemoryViewCollection.java
ldes-server-domain/src/test/java/be/vlaanderen/informatievlaanderen/ldes/server/domain/shacl/InMemoryShaclCollectionTest.java

Makes the memoryShaclCollection event driven as well. In line with viewCollection

Publish events in memoryShaclCollection

---

Dockerfile
docker-compose/config.env
docker-compose/config.local.env
ldes-server-application/pom.xml
ldes-server-infra-mongo/mongock-changeset-5/README.md
ldes-server-infra-mongo/mongock-changeset-5/pom.xml
ldes-server-infra-mongo/mongock-changeset-5/src/main/java/be/vlaanderen/informatievlaanderen/ldes/server/infra/mongo/mongock/changeset5/MemberIngestChange.java
ldes-server-infra-mongo/mongock-changeset-5/src/main/java/be/vlaanderen/informatievlaanderen/ldes/server/infra/mongo/mongock/changeset5/entities/IngestMemberEntity.java
ldes-server-infra-mongo/mongock-changeset-5/src/main/java/be/vlaanderen/informatievlaanderen/ldes/server/infra/mongo/mongock/changeset5/entities/LdesMemberEntityV4.java
ldes-server-infra-mongo/pom.xml

Add mongock change unit for new ingest member module

Implement mongock for ingest member

---

ldes-fragmentisers/ldes-fragmentisers-pagination/src/test/java/be/vlaanderen/informatievlaanderen/ldes/server/fragmentisers/pagination/services/OpenPageProviderTest.java
ldes-fragmentisers/ldes-fragmentisers-substring/src/test/java/be/vlaanderen/informatievlaanderen/ldes/server/fragmentisers/substring/fragment/SubstringFragmentFinderTest.java
ldes-fragmentisers/ldes-fragmentisers-timebased/src/test/java/be/vlaanderen/informatievlaanderen/ldes/server/fragmentisers/timebased/services/OpenFragmentProviderTest.java
ldes-server-domain/src/main/java/be/vlaanderen/informatievlaanderen/ldes/server/domain/ldesfragment/entities/LdesFragment.java
ldes-server-domain/src/main/java/be/vlaanderen/informatievlaanderen/ldes/server/domain/ldesfragment/repository/LdesFragmentRepository.java
ldes-server-domain/src/test/java/be/vlaanderen/informatievlaanderen/ldes/server/domain/ldesfragment/entities/LdesFragmentTest.java
ldes-server-infra-mongo/mongo-repository/src/main/java/be/vlaanderen/informatievlaanderen/ldes/server/infra/mongo/fragment/LdesFragmentMongoRepository.java
ldes-server-infra-mongo/mongo-repository/src/main/java/be/vlaanderen/informatievlaanderen/ldes/server/infra/mongo/fragment/entity/LdesFragmentEntity.java
ldes-server-infra-mongo/mongo-repository/src/test/java/be/vlaanderen/informatievlaanderen/ldes/server/infra/mongo/LdesFragmentMongoRepositoryTest.java
ldes-server-infra-mongo/mongo-repository/src/test/java/be/vlaanderen/informatievlaanderen/ldes/server/infra/mongo/fragment/LdesFragmentRepositorySteps.java

In this PR:
* Removed the attributes softDeleted and immutableTimestamp of LdesFragment
* Deleted two unused methods in LdesFragmentRepository (due to the simplification of retention)

Feat: VSDSPUB-675: Remove softDeleted and immutableTimestamp attributes on LdesFragment

---

docker-compose/config.env
docker-compose/config.local.env
ldes-server-application/pom.xml
ldes-server-infra-mongo/mongock-changeset-6/README.md
ldes-server-infra-mongo/mongock-changeset-6/pom.xml
ldes-server-infra-mongo/mongock-changeset-6/src/main/java/be/vlaanderen/informatievlaanderen/ldes/server/infra/mongo/mongock/changeset6/FragmentUpdaterChange.java
ldes-server-infra-mongo/mongock-changeset-6/src/main/java/be/vlaanderen/informatievlaanderen/ldes/server/infra/mongo/mongock/changeset6/entities/LdesFragmentEntityV3.java
ldes-server-infra-mongo/mongock-changeset-6/src/main/java/be/vlaanderen/informatievlaanderen/ldes/server/infra/mongo/mongock/changeset6/entities/LdesFragmentEntityV4.java
ldes-server-infra-mongo/mongock-changeset-6/src/main/java/be/vlaanderen/informatievlaanderen/ldes/server/infra/mongo/mongock/changeset6/entities/valueobjects/FragmentPair.java
ldes-server-infra-mongo/mongock-changeset-6/src/main/java/be/vlaanderen/informatievlaanderen/ldes/server/infra/mongo/mongock/changeset6/entities/valueobjects/TreeRelation.java
ldes-server-infra-mongo/pom.xml

Creation of Mongock Changeset which removes the softDeleted and immutableTimestamp from LdesFragmentEntity.

Feat: VSDSPUB-676: Mongock updates to remove softDeleted and immutableTimestamp from LdesFragmentEntity

---

ldes-server-domain/src/main/java/be/vlaanderen/informatievlaanderen/ldes/server/domain/eventstream/services/EventStreamServiceImpl.java
ldes-server-domain/src/main/java/be/vlaanderen/informatievlaanderen/ldes/server/domain/view/service/ViewService.java
ldes-server-domain/src/main/java/be/vlaanderen/informatievlaanderen/ldes/server/domain/view/service/ViewServiceImpl.java
ldes-server-domain/src/test/java/be/vlaanderen/informatievlaanderen/ldes/server/domain/eventstream/services/EventStreamServiceImplTest.java
ldes-server-domain/src/test/java/be/vlaanderen/informatievlaanderen/ldes/server/domain/view/service/ViewServiceImplTest.java

Add a default view to a collection when the collection is created

feat: create default pagination when new eventstream is created

---

ldes-server-domain/src/main/java/be/vlaanderen/informatievlaanderen/ldes/server/domain/ldes/retentionpolicy/creation/RetentionPolicyCreatorImpl.java
ldes-server-domain/src/main/java/be/vlaanderen/informatievlaanderen/ldes/server/domain/ldes/retentionpolicy/timebased/TimeBasedRetentionPolicy.java

Removal of debug code in RetentionPolicyCreatorImpl.

Fix: Remove Debug code

---

ldes-server-port-fetch-rest/src/main/java/be/vlaanderen/informatievlaanderen/ldes/server/rest/eventstream/EventStreamController.java
ldes-server-port-fetch-rest/src/main/java/be/vlaanderen/informatievlaanderen/ldes/server/rest/eventstream/OpenApiEventStreamController.java
ldes-server-port-fetch-rest/src/main/java/be/vlaanderen/informatievlaanderen/ldes/server/rest/treenode/OpenApiTreeNodeController.java
ldes-server-port-fetch-rest/src/main/java/be/vlaanderen/informatievlaanderen/ldes/server/rest/treenode/TreeNodeController.java
ldes-server-port-ingest-rest/src/main/java/be/vlaanderen/informatievlaanderen/ldes/server/ingest/rest/MemberIngestController.java
ldes-server-port-ingest-rest/src/main/java/be/vlaanderen/informatievlaanderen/ldes/server/ingest/rest/OpenApiMemberIngestController.java
ldes-server-port-ingestion-rest/src/main/java/be/vlaanderen/informatievlaanderen/ldes/server/ingestion/rest/LdesMemberIngestionController.java
ldes-server-port-ingestion-rest/src/main/java/be/vlaanderen/informatievlaanderen/ldes/server/ingestion/rest/OpenApiLdesMemberIngestionController.java

Open API documentation for ingestion and fetching added

feat: open api docs provided

---

README.md
ldes-fragmentisers/ldes-fragmentisers-geospatial/README.MD
ldes-fragmentisers/ldes-fragmentisers-geospatial/src/test/resources/application-test.yml
ldes-fragmentisers/ldes-fragmentisers-pagination/README.md
ldes-fragmentisers/ldes-fragmentisers-substring/README.MD
ldes-fragmentisers/ldes-fragmentisers-substring/src/main/java/be/vlaanderen/informatievlaanderen/ldes/server/fragmentisers/substring/SubstringFragmentationStrategy.java
ldes-fragmentisers/ldes-fragmentisers-substring/src/main/java/be/vlaanderen/informatievlaanderen/ldes/server/fragmentisers/substring/config/SubstringConfig.java
ldes-fragmentisers/ldes-fragmentisers-substring/src/main/java/be/vlaanderen/informatievlaanderen/ldes/server/fragmentisers/substring/relations/SubstringRelationsAttributer.java
ldes-fragmentisers/ldes-fragmentisers-timebased/src/main/java/be/vlaanderen/informatievlaanderen/ldes/server/fragmentisers/timebased/TimebasedFragmentationStrategyWrapper.java
ldes-fragmentisers/ldes-fragmentisers-timebased/src/main/java/be/vlaanderen/informatievlaanderen/ldes/server/fragmentisers/timebased/config/TimebasedFragmentationConfig.java
ldes-fragmentisers/ldes-fragmentisers-timebased/src/main/java/be/vlaanderen/informatievlaanderen/ldes/server/fragmentisers/timebased/services/TimeBasedFragmentCreator.java
ldes-server-domain/src/main/java/be/vlaanderen/informatievlaanderen/ldes/server/domain/tree/member/entities/Member.java
ldes-server-domain/src/test/resources/eventstream/streams/ldes-with-named-view.ttl
ldes-server-domain/src/test/resources/eventstream/streams/ldes-with-shape.ttl
ldes-server-domain/src/test/resources/eventstream/streams/updated-view.ttl
ldes-server-domain/src/test/resources/eventstream/streams/view.ttl
ldes-server-domain/src/test/resources/eventstream/streams/views.ttl
ldes-server-domain/src/test/resources/viewconverter/view_without_type.ttl
ldes-server-port-admin-rest/README.md
ldes-server-port-admin-rest/src/main/java/be/vlaanderen/informatievlaanderen/ldes/server/admin/rest/controllers/OpenApiAdminViewsRestController.java
ldes-server-port-admin-rest/src/main/java/be/vlaanderen/informatievlaanderen/ldes/server/admin/rest/controllers/OpenApiEventStreamsController.java
ldes-server-port-admin-rest/src/test/resources/view-1.ttl
ldes-server-port-admin-rest/src/test/resources/view-2.ttl
ldes-server-port-admin-rest/src/test/resources/view-without-type.ttl
ldes-server-port-fetch-rest/src/main/java/be/vlaanderen/informatievlaanderen/ldes/server/rest/eventstream/OpenApiEventStreamController.java

Remove old references to example: properties for view definition

fix: update old spec references

---

ldes-server-port-admin-rest/src/main/java/be/vlaanderen/informatievlaanderen/ldes/server/admin/rest/controllers/OpenApiAdminViewsRestController.java

Fix for https://github.com/Informatievlaanderen/VSDS-LDESServer4J/issues/809

Fix response code

---

.github/workflows/release-version.yml

Update the `release-branch-name` from `main` to `develop` in release-version.yml

Fix: Update release-branch-name in release-version.yml

---

ldes-server-admin/src/main/java/be/vlaanderen/informatievlaanderen/ldes/server/admin/domain/eventstream/services/EventStreamServiceImpl.java
ldes-server-admin/src/main/java/be/vlaanderen/informatievlaanderen/ldes/server/admin/domain/view/service/ViewService.java
ldes-server-admin/src/main/java/be/vlaanderen/informatievlaanderen/ldes/server/admin/domain/view/service/ViewServiceImpl.java
ldes-server-admin/src/test/java/be/vlaanderen/informatievlaanderen/ldes/server/admin/domain/eventstream/services/EventStreamServiceImplTest.java
ldes-server-admin/src/test/java/be/vlaanderen/informatievlaanderen/ldes/server/admin/domain/view/service/ViewServiceImplTest.java

Fix for https://github.com/Informatievlaanderen/VSDS-LDESServer4J/issues/893

feat: Remove default view

---

ldes-server-infra-mongo/mongo-retention-repository/src/main/java/be/vlaanderen/informatievlaanderen/ldes/server/retention/entities/MemberPropertiesEntity.java
ldes-server-infra-mongo/mongock-changesets/src/main/java/be/vlaanderen/informatievlaanderen/ldes/server/infra/mongo/mongock/changeset9/entities/MemberPropertiesEntityV1.java

Fix for https://github.com/Informatievlaanderen/VSDS-LDESServer4J/issues/937

Change index to id to make server cosmosdb compatible

---

ldes-fragmentisers/ldes-fragmentisers-timebased-hierarchical/src/main/java/be/vlaanderen/informatievlaanderen/ldes/server/fragmentisers/timebasedhierarchical/constants/Granularity.java
ldes-fragmentisers/ldes-fragmentisers-timebased-hierarchical/src/test/java/be/vlaanderen/informatievlaanderen/ldes/server/fragmentisers/timebasedhierarchical/model/FragmentationTimestampTest.java

Fix for https://github.com/Informatievlaanderen/VSDS-LDESServer4J/issues/944

Fix hour formatting 2pm -> 14

---

ldes-fragmentisers/ldes-fragmentisers-timebased-hierarchical/src/main/java/be/vlaanderen/informatievlaanderen/ldes/server/fragmentisers/timebasedhierarchical/constants/Granularity.java
ldes-fragmentisers/ldes-fragmentisers-timebased-hierarchical/src/main/java/be/vlaanderen/informatievlaanderen/ldes/server/fragmentisers/timebasedhierarchical/constants/TimeBasedConstants.java
ldes-fragmentisers/ldes-fragmentisers-timebased-hierarchical/src/main/java/be/vlaanderen/informatievlaanderen/ldes/server/fragmentisers/timebasedhierarchical/model/FragmentationTimestamp.java
ldes-fragmentisers/ldes-fragmentisers-timebased-hierarchical/src/main/java/be/vlaanderen/informatievlaanderen/ldes/server/fragmentisers/timebasedhierarchical/services/TimeBasedRelationsAttributer.java
ldes-fragmentisers/ldes-fragmentisers-timebased-hierarchical/src/test/java/be/vlaanderen/informatievlaanderen/ldes/server/fragmentisers/timebasedhierarchical/services/TimeBasedRelationsAttributerTest.java

Fix for https://github.com/Informatievlaanderen/VSDS-LDESServer4J/issues/945

Fix xsd types

---

ldes-server-port-fetch-rest/src/main/java/be/vlaanderen/informatievlaanderen/ldes/server/rest/eventstream/EventStreamController.java
ldes-server-port-fetch-rest/src/main/java/be/vlaanderen/informatievlaanderen/ldes/server/rest/eventstream/OpenApiEventStreamController.java
ldes-server-port-fetch-rest/src/main/java/be/vlaanderen/informatievlaanderen/ldes/server/rest/treenode/OpenApiTreeNodeController.java
ldes-server-port-fetch-rest/src/main/java/be/vlaanderen/informatievlaanderen/ldes/server/rest/treenode/TreeNodeController.java

fix: #1026: controllers in fetch module uses now either ResponseEntity or HttpServletResponse

fix: cleaner fetch controller methods

---

ldes-server-admin/src/main/java/be/vlaanderen/informatievlaanderen/ldes/server/admin/spi/EventStreamConverterImpl.java
ldes-server-admin/src/main/java/be/vlaanderen/informatievlaanderen/ldes/server/admin/spi/EventStreamTO.java
ldes-server-port-fetch-rest/src/main/java/be/vlaanderen/informatievlaanderen/ldes/server/rest/treenode/services/EventStreamInfoResponse.java

fix: unexpected behavior when no shacl shape is provided or shacl shape is empty

fix: unexpected empty shacl behavior

---

docs/_features/compaction.md

Rework the page on fragment compaction.

docs: VSDSPUB-1305 - Server: Rework Compaction

---

docs/_configuration/event-stream.md

Update event source documentation

doc: update event source documentation

---

ldes-server-infra-postgres/postgres-maintenance-repository/src/main/java/be/vlaanderen/informatievlaanderen/ldes/server/maintenance/postgres/repository/CompactionPageEntityRepository.java
ldes-server-infra-postgres/postgres-pagination-repository/src/main/java/be/vlaanderen/informatievlaanderen/ldes/server/pagination/postgres/repository/PageMemberEntityRepository.java
ldes-server-integration-test/src/test/java/be/vlaanderen/informatievlaanderen/ldes/server/CompactionServiceSteps.java
ldes-server-integration-test/src/test/java/be/vlaanderen/informatievlaanderen/ldes/server/LdesServerIntegrationTest.java
ldes-server-integration-test/src/test/resources/data/input/eventstreams/compaction/small-paged-observations.ttl
ldes-server-integration-test/src/test/resources/data/input/members/person-state.template.ttl
ldes-server-integration-test/src/test/resources/features/maintenance/compaction.feature

fix: verify compaction only forms pages that respect page size
